language: php

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
      env: DEPENDENCIES='low'
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      env: PHP_VERSION_FORCE=7.4.0
  fast_finish: true

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$PHP_VERSION_FORCE" != "" ]; then composer config platform.php $PHP_VERSION_FORCE; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - vendor/bin/phpspec run -fpretty -v
  - vendor/bin/phpunit
