language: php

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

matrix:
  include:
    - php: 7.2
      dist: bionic
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-req=php'
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer selfupdate --preview
  - export COMPOSER_ROOT_VERSION=dev-master
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpspec run -fpretty -v
  - vendor/bin/phpunit
